sonar.projectKey=imox_cloud_backend          
sonar.projectName=Imox Cloud Backend
sonar.sources=.                             
sonar.host.url=http://localhost:9000
sonar.token=squ_e8f06a5ad116e1555f5b0475640b926fcc571743
sonar.exclusions=**/node_modules/**,**/dist/**

/*
docker run --rm \
  --network host \
  -v "$(pwd):/usr/src" \
  -e SONAR_HOST_URL=http://localhost:9000 \
  -e SONAR_TOKEN=squ_e8f06a5ad116e1555f5b0475640b926fcc571743 \
  sonarsource/sonar-scanner-cli
*/